spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?&serverTimezone=Asia/Seoul
    username: root
    password: 1225
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    virtual-host: /
  jwt:
    secret: govlepel@$&
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false